name: Build Aawaaz macOS
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          cd Aawaaz
          xcodebuild -project "Aawaaz.xcodeproj" -scheme "Aawaaz" -configuration Release CODE_SIGNING_ALLOWED=NO
          mkdir -p ../output
          cp -R build/Release/Aawaaz.app ../output/

      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: Aawaaz-macOS-Build
          path: output/Aawaaz.app
